#!/bin/bash
#SBATCH --job-name=volkov_mpi
#SBATCH --account=van128
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --mem-per-cpu=6GB
#SBATCH --ntasks-per-node=10
#SBATCH --cpus-per-task=1
#SBATCH --time=47:59:59

# NOTE1 MEMORY ::  the mask region takes a lot of memory. Probably should check on how much memory it takes.
#  submit a short job and then use:
#   sstat --job <jobid> --format=JobID,MaxRSS,AveRSS
# NOTE2 number of tasks:: there is a different calculation for each orbital in the mask region. 
#  the code must do 2 FFTs per mask timestep. Use as many tasks as orbitals in the system.
# NOTE3 Disk space :: Saving the PES will use alot of disk space. 

module load cpu/0.17.3b  intel/19.1.3.304/6pv46so fftw/3.3.10/jq4mbmk intel-mkl/2020.4.304/vg6aq26 intel-mpi/2019.10.317/ezrfjne

dftdir=/home/covingcl/codes/varga_dft_code_parallel/release/

cd $SLURM_SUBMIT_DIR

mpirun -n 10 $dftdir/dft > output 2> error
